In [12]:
print("HELLO ALGO-LAB 00")

HELLO ALGO-LAB 00


**Task 2.1**

In [12]:
def find3RDelement(a):
    flag = 2
    for i in range(len(a)):
        if i == flag:
            return a[i]
    print(find3RDelement([1, 2, 7, 4, 5]))
    
ans = find3RDelement([5,6,7,8,8,10])

print(ans)

7


**Task 2.2**

In [13]:
import numpy as np

def doingSomethingImportant(p2, sr, sc, prev, new):
    row = len(p2)
    col = len(p2[0]) if len(p2) > 0 else 0
    
    if sr < 0 or sr >= row or sc < 0 or sc >= col:
        return
    
    if p2[sr][sc] != prev:
        return
    
    p2[sr][sc] = new
    doingSomethingImportant(p2, sr - 1, sc, prev, new)
    doingSomethingImportant(p2, sr + 1, sc, prev, new)
    doingSomethingImportant(p2, sr, sc + 1, prev, new)
    doingSomethingImportant(p2, sr, sc - 1, prev, new)

a2 = [
    [1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 0, 0],
    [1, 0, 0, 1, 1, 0, 1, 1],
    [1, 2, 2, 2, 2, 0, 1, 0],
    [1, 1, 1, 2, 2, 0, 1, 0],
    [1, 1, 1, 2, 2, 2, 2, 0],
    [1, 1, 1, 1, 1, 2, 1, 1],
    [1, 1, 1, 1, 1, 2, 2, 1]
]

x, y = 4, 4
prev = a2[x][y]
new = 3
doingSomethingImportant(a2, x, y, prev, new)

a2 = np.array(a2)
print(a2)


[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 0 0]
 [1 0 0 1 1 0 1 1]
 [1 3 3 3 3 0 1 0]
 [1 1 1 3 3 0 1 0]
 [1 1 1 3 3 3 3 0]
 [1 1 1 1 1 3 1 1]
 [1 1 1 1 1 3 3 1]]


**Task 2.3**

In [14]:
import heapq

def addEdge(adj, u, v, w):
    adj[u].append((v, w))
    adj[v].append((u, w))
    return adj

def doingSomethingImportant(adj, V, src):
    pq = []
    heapq.heappush(pq, (0, src))
    cost = [float('inf')] * V
    cost[src] = 0
    
    while pq:
        d, u = heapq.heappop(pq)
        for v, weight in adj[u]:
            if cost[v] > cost[u] + weight:
                cost[v] = cost[u] + weight
                heapq.heappush(pq, (cost[v], v))
    
    return cost

V = 3
g = [[] for _ in range(V)]
g = addEdge(g, 0, 1, 4)
g = addEdge(g, 0, 2, 5)
g = addEdge(g, 1, 2, 4)

result = [
    (node, cost)
    for node, cost in enumerate(doingSomethingImportant(g, V, 0))
]

print(result)


[(0, 0), (1, 4), (2, 5)]


**Task 3**

In [15]:
def find_peak(matrix):
    if not matrix:
        return None

    rows, columns = len(matrix), len(matrix[0])

    def binary_search(left, right):
        mid = (left + right) // 2
        max_in_column = -1
        max_index = -1

        for i in range(rows):
            if matrix[i][mid] > max_in_column:
                max_in_column = matrix[i][mid]
                max_index = i

        if mid > 0 and matrix[max_index][mid - 1] > matrix[max_index][mid]:
            return binary_search(left, mid - 1)
        elif mid < columns - 1 and matrix[max_index][mid + 1] > matrix[max_index][mid]:
            return binary_search(mid + 1, right)
        else:
            return max_index, mid

    return binary_search(0, columns - 1)

# Example usage:
matrix1 = [
    [0, 1, 0],
    [1, 2, 1],
    [0, 1, 0]
]

matrix2 = [
    [0, 1, 0],
    [0, 0, 0],
    [0, 0, 0]
]

matrix3 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix4 = [
    [5, 3, 7],
    [1, 9, 8],
    [6, 2, 4]
]

print("Matrix 1:")
print(matrix1)
print("Peak Coordinates:", find_peak(matrix1))  # Output: (1, 1)

print("\nMatrix 2:")
print(matrix2)
print("Peak Coordinates:", find_peak(matrix2))  # Output: (0, 1) or (2, 1)

print("\nAdditional Test Case 1:")
print(matrix3)
print("Peak Coordinates:", find_peak(matrix3))  # Output: (2, 2) or any peak in the corners

print("\nAdditional Test Case 2:")
print(matrix4)
print("Peak Coordinates:", find_peak(matrix4))  # Output: (1, 1) or (1, 2) or (2, 1) or (2, 2)


Matrix 1:
[[0, 1, 0], [1, 2, 1], [0, 1, 0]]
Peak Coordinates: (1, 1)

Matrix 2:
[[0, 1, 0], [0, 0, 0], [0, 0, 0]]
Peak Coordinates: (0, 1)

Additional Test Case 1:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Peak Coordinates: (2, 2)

Additional Test Case 2:
[[5, 3, 7], [1, 9, 8], [6, 2, 4]]
Peak Coordinates: (1, 1)
